(() => {
  const $ = id => document.getElementById(id);
  const W=16,H=9,COST=35,MAX_WAVE=5;
  const state={map:[],path:[],pathSet:new Set(),towers:[],enemies:[],bullets:[],particles:[],wave:0,spawned:0,waveActive:false,spawnTimer:0,credits:100,lives:10,score:0,running:false,paused:false,over:true,last:0,raf:0};
  const key=(x,y)=>x+','+y;
  function rng(seed){let n=seed>>>0;return()=>{n=(n*1664525+1013904223)>>>0;return n/4294967296;};}
  function buildMap(){const random=rng(4127);state.map=[];for(let y=0;y<H;y+=1)for(let x=0;x<W;x+=1)state.map.push({x,y,elevation:Math.round(35+random()*50+Math.sin(x*.7+y*.4)*12)});state.path=[];let row=4;for(let x=0;x<W;x+=1){if(x>0&&x<W-1&&random()<.32)row=Math.max(1,Math.min(H-2,row+(random()<.5?-1:1)));state.path.push({x,y:row});if(x<W-1&&row!==state.path[state.path.length-1].y){} }state.pathSet=new Set(state.path.map(cell=>key(cell.x,cell.y)));}
  function reset(){buildMap();state.towers=[];state.enemies=[];state.bullets=[];state.particles=[];state.wave=0;state.spawned=0;state.waveActive=false;state.spawnTimer=0;state.credits=100;state.lives=10;state.score=0;state.running=false;state.paused=false;state.over=true;updateHud();draw();}
  function updateHud(){$('wave').textContent=state.wave+' / '+MAX_WAVE;$('credits').textContent=state.credits;$('lives').textContent=state.lives;$('score').textContent=state.score;$('waveBtn').disabled=!state.running||state.waveActive||state.wave>=MAX_WAVE;$('pause').textContent=state.paused?'Continuar':'Pausar';}
  function status(text){$('status').textContent=text;}
  function start(){reset();state.running=true;state.over=false;$('overlay').hidden=true;state.last=performance.now();status('Construye balizas y lanza la primera oleada cuando estés preparado.');cancelAnimationFrame(state.raf);state.raf=requestAnimationFrame(loop);updateHud();}
  function launchWave(){if(!state.running||state.paused||state.waveActive||state.wave>=MAX_WAVE)return;state.wave+=1;state.spawned=0;state.waveActive=true;state.spawnTimer=0;state.credits+=15;status('Oleada '+state.wave+' en marcha. Coloca balizas en los márgenes.');updateHud();}
  function center(cell,width,height){const pad=16,size=Math.min((width-pad*2)/W,(height-pad*2)/H);return [pad+cell.x*size+size/2,pad+cell.y*size+size/2,size];}
  function validBuild(cell){return cell.x>=0&&cell.y>=0&&cell.x<W&&cell.y<H&&!state.pathSet.has(key(cell.x,cell.y))&&!state.towers.some(t=>t.x===cell.x&&t.y===cell.y);}
  function place(event){if(!state.running||state.paused)return;const rect=$('canvas').getBoundingClientRect(),width=rect.width,height=rect.height,pad=16,size=Math.min((width-pad*2)/W,(height-pad*2)/H),cell={x:Math.floor((event.clientX-rect.left-pad)/size),y:Math.floor((event.clientY-rect.top-pad)/size)};if(!validBuild(cell)){status('Esa casilla pertenece a la ruta o ya tiene una baliza.');return;}if(state.credits<COST){status('Necesitas '+COST+' créditos para construir.');return;}state.credits-=COST;state.towers.push({x:cell.x,y:cell.y,range:3.1,cooldown:0,level:1});burst(cell,'#76e6d0');status('Baliza construida. Sus disparos son automáticos.');updateHud();}
  function spawnEnemy(){const first=state.path[0];const tough=state.wave>=3&&state.spawned%4===0;state.enemies.push({x:first.x,y:first.y,index:0,hp:tough?3+state.wave:1+Math.floor(state.wave/2),maxHp:tough?3+state.wave:1+Math.floor(state.wave/2),speed:tough?.72:.95+state.wave*.08,tough});state.spawned+=1;}
  function moveEnemies(dt){state.enemies.forEach(enemy=>{const next=state.path[Math.min(enemy.index+1,state.path.length-1)];if(!next)return;enemy.x+=(next.x-enemy.x)*dt*enemy.speed*2;enemy.y+=(next.y-enemy.y)*dt*enemy.speed*2;if(Math.hypot(enemy.x-next.x,enemy.y-next.y)<.1){enemy.index+=1;if(enemy.index>=state.path.length-1){enemy.reached=true;state.lives-=1;burst({x:W-1,y:next.y},'#ff8191');}}});state.enemies=state.enemies.filter(enemy=>!enemy.reached&&enemy.hp>0);}
  function towerFire(dt){state.towers.forEach(tower=>{tower.cooldown-=dt;if(tower.cooldown>0)return;let target=null,best=Infinity;state.enemies.forEach(enemy=>{const distance=Math.hypot(enemy.x-tower.x,enemy.y-tower.y);if(distance<=tower.range&&distance<best){best=distance;target=enemy;}});if(target){tower.cooldown=.55;state.bullets.push({x:tower.x,y:tower.y,target,damage:tower.level});}});}
  function moveBullets(dt){state.bullets.forEach(bullet=>{if(!bullet.target||bullet.target.hp<=0){bullet.dead=true;return;}bullet.x+=(bullet.target.x-bullet.x)*dt*9;bullet.y+=(bullet.target.y-bullet.y)*dt*9;if(Math.hypot(bullet.x-bullet.target.x,bullet.y-bullet.target.y)<.15){bullet.target.hp-=bullet.damage;bullet.dead=true;burst({x:Math.round(bullet.target.x),y:Math.round(bullet.target.y)},'#ffd274');if(bullet.target.hp<=0){state.score+=20;state.credits+=10;}}});state.bullets=state.bullets.filter(bullet=>!bullet.dead);}
  function checkEnd(){if(state.lives<=0){finish(false,'El observatorio ha quedado expuesto');return;}if(state.waveActive&&state.spawned>=6+state.wave*2&&state.enemies.length===0){state.waveActive=false;state.credits+=25;status('Oleada superada. +25 créditos.');updateHud();if(state.wave>=MAX_WAVE)finish(true,'Has defendido las cinco oleadas');}}
  function finish(success,message){state.running=false;state.over=true;state.waveActive=false;$('overlayTitle').textContent=success?'Observatorio protegido':'Defensa perdida';$('overlayText').textContent=message+'. Puntuación: '+state.score+'.';$('start').textContent='Jugar de nuevo';$('overlay').hidden=false;status(success?'La carta queda protegida.':'Puedes reiniciar la defensa.');updateHud();draw();}
  function contour(context,cx,cy,size,elevation){context.strokeStyle='#b9e5d833';context.lineWidth=1;for(let line=0;line<3;line+=1){context.beginPath();context.ellipse(cx+Math.sin(elevation+line)*size*.08,cy+Math.cos(elevation+line)*size*.08,size*(.22+line*.12),size*(.12+line*.07),elevation*.03,0,Math.PI*2);context.stroke();}}
  function draw(){const canvas=$('canvas'),rect=canvas.getBoundingClientRect(),dpr=Math.min(window.devicePixelRatio||1,2),width=rect.width,height=rect.height;if(canvas.width!==Math.round(width*dpr)||canvas.height!==Math.round(height*dpr)){canvas.width=Math.round(width*dpr);canvas.height=Math.round(height*dpr);}const context=canvas.getContext('2d');context.setTransform(dpr,0,0,dpr,0,0);context.clearRect(0,0,width,height);const gradient=context.createLinearGradient(0,0,width,height);gradient.addColorStop(0,'#123e52');gradient.addColorStop(1,'#211e3c');context.fillStyle=gradient;context.fillRect(0,0,width,height);state.map.forEach(cell=>{const [cx,cy,size]=center(cell,width,height),hue=cell.elevation>70?'#355b69':cell.elevation>48?'#28645c':'#385b50';context.fillStyle=hue;context.fillRect(cx-size/2+1,cy-size/2+1,size-2,size-2);contour(context,cx,cy,size,cell.elevation);});context.strokeStyle='#ffd274aa';context.lineWidth=5;context.lineCap='round';context.beginPath();state.path.forEach((cell,index)=>{const [cx,cy]=center(cell,width,height);index?context.lineTo(cx,cy):context.moveTo(cx,cy);});context.stroke();context.strokeStyle='#7a5c3d';context.lineWidth=2;context.stroke();state.towers.forEach(tower=>{const [cx,cy,size]=center(tower,width,height);context.strokeStyle='#76e6d033';context.beginPath();context.arc(cx,cy,size*tower.range,0,Math.PI*2);context.stroke();context.fillStyle='#76e6d0';context.shadowColor='#76e6d0';context.shadowBlur=18;context.beginPath();context.arc(cx,cy,size*.23,0,Math.PI*2);context.fill();context.shadowBlur=0;context.fillStyle='#09293a';context.beginPath();context.arc(cx,cy,size*.08,0,Math.PI*2);context.fill();});state.enemies.forEach(enemy=>{const [cx,cy,size]=center({x:enemy.x,y:enemy.y},width,height);context.fillStyle=enemy.tough?'#c18aff':'#ff8191';context.shadowColor=context.fillStyle;context.shadowBlur=12;context.beginPath();context.moveTo(cx,cy-size*.26);context.lineTo(cx+size*.25,cy);context.lineTo(cx,cy+size*.26);context.lineTo(cx-size*.25,cy);context.closePath();context.fill();context.shadowBlur=0;context.fillStyle='#071522';context.fillRect(cx-size*.25,cy-size*.4,size*.5,3);context.fillStyle='#72e6d0';context.fillRect(cx-size*.25,cy-size*.4,size*.5*Math.max(0,enemy.hp/enemy.maxHp),3);});state.bullets.forEach(bullet=>{const [cx,cy]=center({x:bullet.x,y:bullet.y},width,height);context.fillStyle='#ffd274';context.beginPath();context.arc(cx,cy,3,0,Math.PI*2);context.fill();});state.particles.forEach(p=>{const [cx,cy]=center(p.cell,width,height);context.globalAlpha=p.life;context.fillStyle=p.color;context.beginPath();context.arc(cx+p.x,cy+p.y,2+p.life*3,0,Math.PI*2);context.fill();});context.globalAlpha=1;context.fillStyle='#efffffcc';context.font='12px system-ui';context.fillText('N',10,18);context.fillText('BALIZAS '+state.towers.length,width-100,18);}
  function burst(cell,color){for(let i=0;i<7;i+=1){const angle=i/7*Math.PI*2;state.particles.push({cell:{x:cell.x,y:cell.y},x:0,y:0,vx:Math.cos(angle)*16,vy:Math.sin(angle)*16,life:.65,color});}}
  function loop(now){const dt=Math.min(.05,(now-state.last)/1000||0);state.last=now;if(state.running&&!state.paused){if(state.waveActive){state.spawnTimer-=dt;if(state.spawned<6+state.wave*2&&state.spawnTimer<=0){spawnEnemy();state.spawnTimer=.8-Math.min(.25,state.wave*.04);}}moveEnemies(dt);towerFire(dt);moveBullets(dt);checkEnd();}state.particles.forEach(p=>{p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;});state.particles=state.particles.filter(p=>p.life>0);draw();if(state.running||!state.over)state.raf=requestAnimationFrame(loop);}
  $('start').addEventListener('click',start);$('waveBtn').addEventListener('click',launchWave);$('pause').addEventListener('click',()=>{if(!state.running)return;state.paused=!state.paused;status(state.paused?'Pausa activa: los drones se detienen.':'Defensa reanudada.');updateHud();});$('reset').addEventListener('click',reset);$('canvas').addEventListener('pointerdown',place);$('canvas').addEventListener('contextmenu',event=>event.preventDefault());window.addEventListener('resize',draw);window.addEventListener('keydown',event=>{const name=event.key.toLowerCase();if(name==='p')$('pause').click();if(name==='n')launchWave();});reset();
})();
