const $=id=>document.getElementById(id),canvas=$('board'),ctx=canvas.getContext('2d'),W=canvas.width,H=canvas.height,COLS=12,ROWS=8,TILE=W/COLS;let state='ready',turn=1,score=0,energy=3,best=Number(localStorage.getItem('carto-tactics-best')||0),grid=[],player={x:1,y:4},rival={x:10,y:3},beacons=[],particles=[],random=()=>Math.random();
function reset(){turn=1;score=0;energy=3;state='ready';grid=Array.from({length:ROWS},(_,y)=>Array.from({length:COLS},(_,x)=>{const n=random();return x===0||y===0||x===COLS-1||y===ROWS-1?'rock':n<.12?'water':n<.25?'forest':n<.31?'rock':'grass'}));for(let y=3;y<6;y++)for(let x=1;x<4;x++)grid[y][x]='grass';for(let y=2;y<6;y++)for(let x=9;x<11;x++)grid[y][x]='grass';beacons=[{x:4,y:2,taken:false},{x:6,y:6,taken:false},{x:9,y:4,taken:false}];player={x:1,y:4};rival={x:10,y:3};particles=[];updateHud();draw()}
function updateHud(){const found=beacons.filter(b=>b.taken).length;$('turn').textContent=turn;$('beacons').textContent=`${found} / ${beacons.length}`;$('score').textContent=score.toLocaleString('es-ES');$('energy').textContent=energy;$('objective').textContent=found===3?'Territorio asegurado':'Captura las balizas';}
function start(){reset();state='running';$('message').classList.add('hidden');$('end').disabled=false;$('status').textContent='Tu turno: desplázate una casilla por acción.';draw()}
function terrain(x,y){return grid[y]?.[x]||'rock'}function canMove(x,y){return x>=0&&y>=0&&x<COLS&&y<ROWS&&!['water','rock'].includes(terrain(x,y))&&!(x===rival.x&&y===rival.y)}
function move(dx,dy){if(state!=='running'||energy<=0)return;const x=player.x+dx,y=player.y+dy;if(Math.abs(dx)+Math.abs(dy)!==1)return;if(!canMove(x,y)){$('status').textContent='Ese terreno está bloqueado o ocupado.';return}player={x,y};energy--;const beacon=beacons.find(b=>b.x===x&&b.y===y);if(beacon&&!beacon.taken){beacon.taken=true;score+=500;burst(x,y,'#ffd77b',18);$('status').textContent='Baliza capturada. El rival se mueve al terminar turno.'}else $('status').textContent=`Movimiento realizado. Te quedan ${energy} acciones.`;updateHud();draw();if(beacons.every(b=>b.taken))finish(true)}
function endTurn(){if(state!=='running')return;aiMove();turn++;energy=3;updateHud();draw();if(player.x===rival.x&&player.y===rival.y)finish(false)}
function aiMove(){const target=beacons.filter(b=>!b.taken).sort((a,b)=>Math.hypot(a.x-rival.x,a.y-rival.y)-Math.hypot(b.x-rival.x,b.y-rival.y))[0];if(!target)return;const options=[{x:Math.sign(target.x-rival.x),y:0},{x:0,y:Math.sign(target.y-rival.y)},{x:0,y:Math.sign(target.y-rival.y)*-1},{x:Math.sign(target.x-rival.x)*-1,y:0}].filter(o=>canMove(rival.x+o.x,rival.y+o.y));if(options[0]){rival.x+=options[0].x;rival.y+=options[0].y}const beacon=beacons.find(b=>b.x===rival.x&&b.y===rival.y);if(beacon&&!beacon.taken){beacon.taken=true;score=Math.max(0,score-200);$('status').textContent='El rival ha tomado una baliza.'}}
function finish(win){state=win?'won':'lost';$('end').disabled=true;if(win){score+=Math.max(0,600-turn*25);if(!best||turn<best){best=turn;localStorage.setItem('carto-tactics-best',best)}}$('message').classList.remove('hidden');$('message').querySelector('h2').textContent=win?'Territorio asegurado':'La expedición fue interceptada';$('message').querySelector('p:not(.eyebrow)').textContent=win?`Has capturado las tres balizas en ${turn} turnos con ${score.toLocaleString('es-ES')} puntos.`:'El rival ha alcanzado tu posición. Replantea la ruta y vuelve a intentarlo.';$('start').textContent='Repetir operación';$('status').textContent=win?'Misión completada.':'Misión terminada.';updateHud();draw()}
function burst(x,y,color,count){for(let i=0;i<count;i++)particles.push({x:x+.5,y:y+.5,vx:(Math.random()-.5)*3,vy:(Math.random()-.5)*3,life:.8,color})}
function draw(){ctx.clearRect(0,0,W,H);for(let y=0;y<ROWS;y++)for(let x=0;x<COLS;x++)drawTile(x,y,terrain(x,y));beacons.forEach(drawBeacon);drawUnit(player,'#75e9d2','Tu unidad');drawUnit(rival,'#ff87bd','Rival');particles.forEach(p=>{ctx.globalAlpha=p.life/.8;ctx.fillStyle=p.color;ctx.fillRect(p.x*TILE,p.y*TILE,5,5)});ctx.globalAlpha=1;if(state==='paused'){ctx.fillStyle='#09101eaa';ctx.fillRect(0,0,W,H);ctx.fillStyle='#fff';ctx.textAlign='center';ctx.font='700 32px system-ui';ctx.fillText('PAUSA',W/2,H/2);ctx.textAlign='start'}}
function drawTile(x,y,type){const colors={grass:['#456d5c','#6b9a6b'],forest:['#234f4b','#397963'],water:['#286289','#57a5be'],rock:['#50556a','#858797']}[type];const px=x*TILE,py=y*TILE;ctx.fillStyle=colors[0];ctx.fillRect(px,py,TILE+1,TILE+1);ctx.strokeStyle=colors[1];ctx.globalAlpha=.55;ctx.lineWidth=1;if(type==='water'){for(let yy=9;yy<TILE;yy+=14){ctx.beginPath();ctx.moveTo(px+4,py+yy);ctx.quadraticCurveTo(px+TILE/2,py+yy-5,px+TILE-4,py+yy);ctx.stroke()}}else if(type==='forest'){for(let i=0;i<3;i++){const tx=px+8+i*13;ctx.beginPath();ctx.moveTo(tx,py+28);ctx.lineTo(tx+7,py+10);ctx.lineTo(tx+14,py+28);ctx.stroke()}}else if(type==='rock'){ctx.beginPath();ctx.moveTo(px+8,py+27);ctx.lineTo(px+20,py+9);ctx.lineTo(px+34,py+25);ctx.stroke()}else ctx.fillRect(px+13+(x*7+y)%18,py+10+(x*3+y)%18,3,3);ctx.globalAlpha=1;ctx.strokeStyle='#bde8d133';ctx.strokeRect(px,py,TILE,TILE)}
function drawBeacon(b){const x=(b.x+.5)*TILE,y=(b.y+.5)*TILE;ctx.save();ctx.translate(x,y);ctx.shadowBlur=18;ctx.shadowColor='#ffd77b';ctx.fillStyle=b.taken?'#fff9':'#ffd77b';ctx.beginPath();ctx.arc(0,0,17+Math.sin(turn*.8+b.x)*2,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='#2c2630';ctx.font='bold 19px system-ui';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(b.taken?'✓':'✦',0,1);ctx.restore()}
function drawUnit(unit,color,label){const x=(unit.x+.5)*TILE,y=(unit.y+.5)*TILE;ctx.save();ctx.translate(x,y);ctx.shadowBlur=18;ctx.shadowColor=color;ctx.fillStyle=color;ctx.beginPath();ctx.moveTo(0,-19);ctx.lineTo(17,13);ctx.lineTo(0,8);ctx.lineTo(-17,13);ctx.closePath();ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='#101a2e';ctx.beginPath();ctx.arc(0,-3,5,0,Math.PI*2);ctx.fill();ctx.restore()}
function loop(){particles.forEach(p=>{p.x+=p.vx*.016;p.y+=p.vy*.016;p.life-=.016});particles=particles.filter(p=>p.life>0);draw();requestAnimationFrame(loop)}
canvas.addEventListener('pointerdown',event=>{if(state!=='running')return;const rect=canvas.getBoundingClientRect();const x=Math.floor((event.clientX-rect.left)*W/rect.width/TILE),y=Math.floor((event.clientY-rect.top)*H/rect.height/TILE);move(x-player.x,y-player.y)});window.addEventListener('keydown',event=>{const keys={ArrowUp:[0,-1],w:[0,-1],ArrowDown:[0,1],s:[0,1],ArrowLeft:[-1,0],a:[-1,0],ArrowRight:[1,0],d:[1,0]};if(keys[event.key]){event.preventDefault();move(...keys[event.key])}if(event.key==='Enter')endTurn()});$('end').addEventListener('click',endTurn);$('new').addEventListener('click',start);$('start').addEventListener('click',start);reset();requestAnimationFrame(loop);
