(() => {
  const $ = id => document.getElementById(id);
  const W = 18, H = 11, TARGET = 5;
  const state = { world: [], beacons: new Set(), found: new Set(), storms: new Set(), revealed: new Set(), player: { x: 1, y: 1 }, battery: 100, score: 0, moves: 0, running: false, paused: false, over: true, scanPulse: 0, particles: [], seed: 24, last: 0, raf: 0, best: Number(localStorage.getItem('geo-rescue-best') || 0) };
  const key = (x, y) => x + ',' + y;
  const parseKey = value => { const [x, y] = value.split(',').map(Number); return { x, y }; };
  function rng(seed) { let value = seed >>> 0; return () => { value = (value * 1664525 + 1013904223) >>> 0; return value / 4294967296; }; }
  function inside(x, y) { return x >= 0 && y >= 0 && x < W && y < H; }
  function terrainAt(x, y) { return state.world[y * W + x]; }
  function makeWorld(seed) {
    const random = rng(seed); const world = [];
    for (let y = 0; y < H; y += 1) for (let x = 0; x < W; x += 1) {
      const roll = random(), elevation = Math.round((Math.sin(x * .75 + seed) + Math.cos(y * .9 - seed) + random() * 2) * 18 + 50);
      world.push({ x, y, elevation, terrain: roll < .10 ? 'water' : roll < .23 ? 'rock' : roll < .35 ? 'sand' : 'grass' });
    }
    world[1 * W + 1].terrain = 'grass';
    return world;
  }
  function resetWorld() {
    state.world = makeWorld(state.seed); state.beacons = new Set(); state.found = new Set(); state.storms = new Set(); state.revealed = new Set(); state.player = { x: 1, y: 1 }; state.battery = 100; state.score = 0; state.moves = 0; state.scanPulse = 0; state.particles = [];
    const random = rng(state.seed + 91);
    while (state.beacons.size < TARGET) { const x = 2 + Math.floor(random() * (W - 3)), y = 1 + Math.floor(random() * (H - 2)), cell = terrainAt(x, y); if (cell.terrain !== 'water' && cell.terrain !== 'rock' && Math.abs(x - 1) + Math.abs(y - 1) > 7) state.beacons.add(key(x, y)); }
    revealAround(1);
    updateHud(); draw();
  }
  function revealAround(radius) { for (let y = 0; y < H; y += 1) for (let x = 0; x < W; x += 1) if (Math.hypot(x - state.player.x, y - state.player.y) <= radius + .45) state.revealed.add(key(x, y)); }
  function updateHud() { $('beacons').textContent = state.found.size + ' / ' + TARGET; $('battery').textContent = Math.max(0, Math.round(state.battery)) + ' %'; $('score').textContent = state.score; $('best').textContent = Math.max(state.best, state.score); }
  function status(text) { $('status').textContent = text; }
  function start() { state.seed = Math.floor(Math.random() * 100000); state.running = true; state.paused = false; state.over = false; $('overlay').hidden = true; $('pause').textContent = 'Pausar'; resetWorld(); status('Misión iniciada. Escanea y busca las balizas ocultas.'); state.last = performance.now(); cancelAnimationFrame(state.raf); state.raf = requestAnimationFrame(loop); }
  function finish(success, message) { state.running = false; state.over = true; const finalScore = success ? state.score + Math.max(0, Math.round(state.battery)) : state.score; state.score = finalScore; if (finalScore > state.best) { state.best = finalScore; localStorage.setItem('geo-rescue-best', String(finalScore)); } updateHud(); $('overlayTitle').textContent = success ? 'Zona asegurada' : 'Misión abortada'; $('overlayText').textContent = message + ' Puntuación: ' + finalScore + '.'; $('start').textContent = 'Nueva misión'; $('overlay').hidden = false; status(success ? 'Todas las balizas han sido recuperadas.' : 'La expedición necesita una nueva salida.'); draw(); }
  function blocked(x, y) { const cell = terrainAt(x, y); return !cell || cell.terrain === 'water' || cell.terrain === 'rock'; }
  function move(dx, dy, boosted = false) {
    if (!state.running || state.paused) return;
    const steps = boosted ? 2 : 1; let moved = false;
    for (let i = 0; i < steps; i += 1) { const x = state.player.x + dx, y = state.player.y + dy; if (!inside(x, y) || blocked(x, y)) { status('El rover no puede atravesar agua ni roca.'); break; } state.player = { x, y }; state.moves += 1; state.battery -= boosted ? 4 : 2; moved = true; burst(state.player, boosted ? '#ffd273' : '#72e7d2'); const point = key(x, y); if (state.beacons.has(point) && !state.found.has(point)) { state.found.add(point); state.score += 100; status('¡Baliza recuperada! Sigue buscando las restantes.'); } }
    if (!moved) return; revealAround(2); if (state.moves % 4 === 0) stormTurn(); updateHud(); checkEnd();
  }
  function scan() { if (!state.running || state.paused || state.battery < 4) return; state.battery -= 4; state.scanPulse = 1; revealAround(4); state.score += 5; let nearby = 0; state.beacons.forEach(point => { const cell = parseKey(point); if (!state.found.has(point) && Math.hypot(cell.x - state.player.x, cell.y - state.player.y) < 4.5) nearby += 1; }); status(nearby ? 'El escáner detecta ' + nearby + ' señal' + (nearby === 1 ? '' : 'es') + ' cerca.' : 'Sin señales próximas. Revisa las zonas no exploradas.'); updateHud(); checkEnd(); }
  function boost() { if (state.battery < 8) { status('No hay batería suficiente para el impulso.'); return; } move(0, -1, true); }
  function stormTurn() { const random = rng(state.seed + state.moves * 13); const candidates = state.world.filter(cell => Math.hypot(cell.x - state.player.x, cell.y - state.player.y) > 2 && cell.terrain !== 'water' && cell.terrain !== 'rock'); if (candidates.length) { const cell = candidates[Math.floor(random() * candidates.length)]; state.storms.add(key(cell.x, cell.y)); burst(cell, '#b994ff'); } state.storms.forEach(point => { const cell = parseKey(point); if (Math.hypot(cell.x - state.player.x, cell.y - state.player.y) < 1.1) state.battery -= 10; }); }
  function checkEnd() { if (state.found.size >= TARGET) finish(true, 'Has localizado todas las señales y cartografiado el área'); else if (state.battery <= 0) finish(false, 'El rover se ha quedado sin batería'); }
  function center(cell, width, height) { const pad = 18, size = Math.min((width - pad * 2) / W, (height - pad * 2) / H); return [pad + cell.x * size + size / 2, pad + cell.y * size + size / 2, size]; }
  function roundedRect(context, x, y, width, height, radius) { if (context.roundRect) { context.roundRect(x, y, width, height, radius); return; } const r = Math.min(radius, width / 2, height / 2); context.moveTo(x + r, y); context.arcTo(x + width, y, x + width, y + height, r); context.arcTo(x + width, y + height, x, y + height, r); context.arcTo(x, y + height, x, y, r); context.arcTo(x, y, x + width, y, r); }
  function draw() {
    const canvas = $('canvas'), rect = canvas.getBoundingClientRect(), dpr = Math.min(window.devicePixelRatio || 1, 2), width = rect.width, height = rect.height; if (canvas.width !== Math.round(width * dpr) || canvas.height !== Math.round(height * dpr)) { canvas.width = Math.round(width * dpr); canvas.height = Math.round(height * dpr); }
    const context = canvas.getContext('2d'); context.setTransform(dpr, 0, 0, dpr, 0, 0); context.clearRect(0, 0, width, height); const bg = context.createLinearGradient(0, 0, width, height); bg.addColorStop(0, '#0b2b3d'); bg.addColorStop(1, '#121b36'); context.fillStyle = bg; context.fillRect(0, 0, width, height);
    state.world.forEach(cell => { const [cx, cy, size] = center(cell, width, height), point = key(cell.x, cell.y), visible = state.revealed.has(point); context.fillStyle = visible ? ({water:'#174c72',rock:'#525674',sand:'#8b7351',grass:'#286454'}[cell.terrain]) : '#102033'; context.globalAlpha = visible ? 1 : .86; context.fillRect(cx - size / 2 + 1, cy - size / 2 + 1, size - 2, size - 2); context.globalAlpha = 1; if (visible && cell.terrain !== 'water') { context.strokeStyle = cell.terrain === 'rock' ? '#b9b7cc55' : '#8be2c933'; context.lineWidth = 1; for (let line = 0; line < 2; line += 1) { context.beginPath(); context.arc(cx + (line - .5) * size * .12, cy, size * (.18 + line * .12), 0, Math.PI); context.stroke(); } } if (state.storms.has(point) && visible) { context.fillStyle = '#a58cff88'; context.beginPath(); context.arc(cx, cy, size * .3, 0, Math.PI * 2); context.fill(); context.strokeStyle = '#d1bfff'; context.stroke(); } if (state.beacons.has(point) && !state.found.has(point) && visible) { context.fillStyle = '#ffd273'; context.shadowColor = '#ffd273'; context.shadowBlur = 15; context.beginPath(); context.arc(cx, cy, size * .16, 0, Math.PI * 2); context.fill(); context.shadowBlur = 0; } if (state.found.has(point)) { context.strokeStyle = '#72e7d2'; context.lineWidth = 3; context.beginPath(); context.arc(cx, cy, size * .27, 0, Math.PI * 2); context.stroke(); } });
    const [px, py, size] = center(state.player, width, height); context.save(); context.translate(px, py); context.shadowColor = '#72e7d2'; context.shadowBlur = 18; context.fillStyle = '#72e7d2'; context.beginPath(); roundedRect(context, -size * .22, -size * .16, size * .44, size * .32, size * .1); context.fill(); context.shadowBlur = 0; context.fillStyle = '#09243b'; context.fillRect(-size * .1, -size * .08, size * .2, size * .16); context.fillStyle = '#e8ffff'; context.beginPath(); context.arc(0, -size * .2, size * .06, 0, Math.PI * 2); context.fill(); context.restore();
    if (state.scanPulse > 0) { context.globalAlpha = state.scanPulse; context.strokeStyle = '#72e7d2'; context.lineWidth = 3; context.beginPath(); context.arc(px, py, size * (1.1 + (1 - state.scanPulse) * 3.3), 0, Math.PI * 2); context.stroke(); context.globalAlpha = 1; }
    state.particles.forEach(particle => { const [cx, cy] = center(particle.cell, width, height); context.globalAlpha = particle.life; context.fillStyle = particle.color; context.beginPath(); context.arc(cx + particle.x, cy + particle.y, 2 + particle.life * 3, 0, Math.PI * 2); context.fill(); }); context.globalAlpha = 1; context.fillStyle = '#efffffcc'; context.font = '12px system-ui'; context.fillText('N', 10, 18); context.fillText('ESCÁNER ' + (state.scanPulse > 0 ? 'ACTIVO' : 'LISTO'), width - 118, 18);
  }
  function burst(cell, color) { for (let i = 0; i < 8; i += 1) { const angle = i / 8 * Math.PI * 2; state.particles.push({ cell:{x:cell.x,y:cell.y}, x:0, y:0, vx:Math.cos(angle) * 15, vy:Math.sin(angle) * 15, life:.8, color }); } }
  function cellFromEvent(event) { const rect = $('canvas').getBoundingClientRect(), x = event.clientX - rect.left, y = event.clientY - rect.top, pad = 18, size = Math.min((rect.width - pad * 2) / W, (rect.height - pad * 2) / H); return { x: Math.floor((x - pad) / size), y: Math.floor((y - pad) / size) }; }
  function tapMove(event) { if (!state.running || state.paused) return; const target = cellFromEvent(event), dx = target.x - state.player.x, dy = target.y - state.player.y; if (Math.abs(dx) + Math.abs(dy) === 1) move(Math.sign(dx), Math.sign(dy)); else status('Toca una casilla contigua para mover el rover.'); }
  function loop(now) { const dt = Math.min(.05, (now - state.last) / 1000 || 0); state.last = now; state.scanPulse = Math.max(0, state.scanPulse - dt * 1.5); state.particles.forEach(p => { p.life -= dt; p.x += p.vx * dt; p.y += p.vy * dt; }); state.particles = state.particles.filter(p => p.life > 0); draw(); if (state.running || !state.over) state.raf = requestAnimationFrame(loop); }
  function resize() { draw(); }
  document.querySelectorAll('[data-move]').forEach(button => button.addEventListener('click', () => { const direction = {up:[0,-1],down:[0,1],left:[-1,0],right:[1,0]}[button.dataset.move]; move(direction[0], direction[1]); }));
  $('start').addEventListener('click', start); $('scan').addEventListener('click', scan); $('boost').addEventListener('click', boost); $('pause').addEventListener('click', () => { if (!state.running) return; state.paused = !state.paused; $('pause').textContent = state.paused ? 'Continuar' : 'Pausar'; status(state.paused ? 'Pausa activa: la tormenta queda detenida.' : 'Misión reanudada.'); }); $('canvas').addEventListener('pointerdown', tapMove); $('canvas').addEventListener('contextmenu', event => event.preventDefault()); window.addEventListener('resize', resize); window.addEventListener('keydown', event => { const keyName = event.key.toLowerCase(); const directions = {arrowup:[0,-1],w:[0,-1],arrowdown:[0,1],s:[0,1],arrowleft:[-1,0],a:[-1,0],arrowright:[1,0],d:[1,0]}; if (directions[keyName]) { event.preventDefault(); move(directions[keyName][0], directions[keyName][1]); } if (keyName === 'f') scan(); if (keyName === 'b') boost(); if (keyName === 'p') $('pause').click(); }); resetWorld(); resize();
})();
