const canvas=document.getElementById('canvas'),ctx=canvas.getContext('2d'),$=id=>document.getElementById(id);const W=canvas.width,H=canvas.height;let running=false,paused=false,last=0,score=0,best=Number(localStorage.getItem('meteor-best')||0),level=1,spawn=0,player,rocks=[],particles=[],keys=new Set();$('best').textContent=best;
function reset(){score=0;level=1;spawn=0;rocks=[];particles=[];player={x:W/2,y:H-58,w:32,h:24,speed:390};updateHud()}function updateHud(){$('score').textContent=Math.floor(score);$('best').textContent=best;$('level').textContent=level}
function start(){reset();running=true;paused=false;$('message').hidden=true;$('pause').disabled=false;$('pause').textContent='Pausar';last=performance.now();requestAnimationFrame(loop)}
function gameOver(){running=false;$('pause').disabled=true;if(Math.floor(score)>best){best=Math.floor(score);localStorage.setItem('meteor-best',best)}updateHud();$('message').hidden=false;$('message').innerHTML=`<strong>Partida terminada</strong><span>Has conseguido ${Math.floor(score)} puntos.</span><button id="start" class="primary">Jugar de nuevo</button>`;$('start').addEventListener('click',start);beep(130,.18)}
function spawnRock(){const r=13+Math.random()*20;rocks.push({x:r+Math.random()*(W-2*r),y:-r,r,vy:95+Math.random()*80+level*12,rot:Math.random()*6,spin:(Math.random()-.5)*2});}
function update(dt){const dir=(keys.has('ArrowRight')||keys.has('d')?1:0)-(keys.has('ArrowLeft')||keys.has('a')?1:0);player.x=Math.max(player.w/2,Math.min(W-player.w/2,player.x+dir*player.speed*dt));spawn-=dt;if(spawn<=0){spawnRock();spawn=Math.max(.22,.78-level*.045)}score+=dt*10;level=1+Math.floor(score/120);for(const r of rocks){r.y+=r.vy*dt;r.rot+=r.spin*dt}rocks=rocks.filter(r=>r.y<H+50);for(const p of particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.life-=dt}particles=particles.filter(p=>p.life>0);for(const r of rocks){if(Math.hypot(r.x-player.x,r.y-player.y)<r.r+16){for(let i=0;i<18;i++)particles.push({x:player.x,y:player.y,vx:(Math.random()-.5)*220,vy:(Math.random()-.5)*220,life:.7});gameOver();break}}updateHud()}
function draw(){ctx.clearRect(0,0,W,H);ctx.fillStyle='#080b1b';ctx.fillRect(0,0,W,H);for(let i=0;i<70;i++){const x=(i*137)%W,y=(i*71+Math.floor(score*2))%H;ctx.fillStyle=i%8===0?'#7af1e2aa':'#ffffff55';ctx.fillRect(x,y,2,2)}for(const r of rocks){ctx.save();ctx.translate(r.x,r.y);ctx.rotate(r.rot);ctx.fillStyle='#cf668e';ctx.strokeStyle='#ffb6ca';ctx.lineWidth=2;ctx.beginPath();for(let i=0;i<8;i++){const a=i*Math.PI/4,rr=r.r*(.78+((i*17)%5)/10);ctx.lineTo(Math.cos(a)*rr,Math.sin(a)*rr)}ctx.closePath();ctx.fill();ctx.stroke();ctx.restore()}ctx.save();ctx.translate(player.x,player.y);ctx.fillStyle='#7af1e2';ctx.shadowColor='#7af1e2';ctx.shadowBlur=18;ctx.beginPath();ctx.moveTo(0,-18);ctx.lineTo(17,14);ctx.lineTo(0,8);ctx.lineTo(-17,14);ctx.closePath();ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='#081425';ctx.beginPath();ctx.arc(0,-3,4,0,Math.PI*2);ctx.fill();ctx.restore();for(const p of particles){ctx.globalAlpha=Math.max(0,p.life);ctx.fillStyle='#ffe28a';ctx.fillRect(p.x,p.y,4,4)}ctx.globalAlpha=1;if(paused&&running){ctx.fillStyle='#080b1bcc';ctx.fillRect(0,0,W,H);ctx.fillStyle='#f2f5ff';ctx.font='700 30px system-ui';ctx.textAlign='center';ctx.fillText('PAUSA',W/2,H/2)} }
function loop(t){if(!running)return;const dt=Math.min(.04,(t-last)/1000);last=t;if(!paused)update(dt);draw();requestAnimationFrame(loop)}function beep(freq,duration){try{const a=new AudioContext(),o=a.createOscillator(),g=a.createGain();o.frequency.value=freq;g.gain.value=.03;o.connect(g).connect(a.destination);o.start();o.stop(a.currentTime+duration)}catch{}}
document.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','a','d','A','D'].includes(e.key))keys.add(e.key);if(e.key===' '&&running){paused=!paused;$('pause').textContent=paused?'Continuar':'Pausar'}});document.addEventListener('keyup',e=>keys.delete(e.key));$('start').addEventListener('click',start);$('pause').addEventListener('click',()=>{if(running){paused=!paused;$('pause').textContent=paused?'Continuar':'Pausar'}});$('restart').addEventListener('click',start);document.querySelectorAll('.touch button').forEach(b=>{const k=b.dataset.key;b.addEventListener('pointerdown',()=>keys.add(k));['pointerup','pointercancel','pointerleave'].forEach(ev=>b.addEventListener(ev,()=>keys.delete(k)))});reset();draw();
