(() => {
  const $ = id => document.getElementById(id); const canvas = $('board'); const ctx = canvas.getContext('2d');
  const cols = 16, rows = 10, tile = canvas.width / cols; const bestKey = 'browser-arcade-ridge-recon-best';
  let seed = 7, terrain, visible, targets, sentinels, storms, player, base, active = false, turn = 1, energy = 4, score = 0, discoveries = 0, animation;
  const dirs = { up: [0, -1], down: [0, 1], left: [-1, 0], right: [1, 0] };
  function rng() { seed = (seed * 1664525 + 1013904223) >>> 0; return seed / 4294967296; }
  function clamp(value, min, max) { return Math.max(min, Math.min(max, value)); }
  function key(x, y) { return `${x},${y}`; }
  function safe(value) { return String(value ?? '').replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char])); }
  function setStatus(text) { $('status').textContent = text; }
  function makeMap() { seed = 7 + Math.floor(Math.random() * 4000); terrain = []; visible = new Set(); base = { x: 1, y: 8 }; player = { ...base }; targets = [{ x: 13, y: 1, found: false }, { x: 5, y: 3, found: false }, { x: 12, y: 7, found: false }]; sentinels = [{ x: 14, y: 8 }, { x: 9, y: 1 }]; storms = [{ x: 4, y: 6 }, { x: 10, y: 4 }]; for (let y = 0; y < rows; y++) for (let x = 0; x < cols; x++) { const roll = rng(); terrain.push(roll < .1 ? 'water' : roll < .25 ? 'forest' : roll < .36 ? 'ridge' : roll < .41 ? 'ruin' : 'plain'); } [base, player, ...targets, ...sentinels, ...storms].forEach(point => terrain[point.y * cols + point.x] = 'plain'); reveal(1); }
  function reveal(radius) { for (let y = 0; y < rows; y++) for (let x = 0; x < cols; x++) if (Math.hypot(x - player.x, y - player.y) <= radius + .35) visible.add(key(x, y)); }
  function terrainPassable(x, y) { return x >= 0 && x < cols && y >= 0 && y < rows && terrain[y * cols + x] !== 'water'; }
  function targetAt(x, y) { return targets.find(target => target.x === x && target.y === y); }
  function sentinelAt(x, y) { return sentinels.find(sentinel => sentinel.x === x && sentinel.y === y); }
  function stormAt(x, y) { return storms.some(storm => storm.x === x && storm.y === y); }
  function updateHud() { $('turn').textContent = turn; $('energy').textContent = energy; $('discoveries').textContent = `${discoveries} / 3`; $('score').textContent = score; $('scan').disabled = !active || energy < 2; $('end').disabled = !active; }
  function drawTile(x, y, type) { const px = x * tile, py = y * tile; const colors = { plain: ['#173b39', '#0d2b31'], forest: ['#1d523c', '#0f302e'], ridge: ['#465244', '#243b39'], ruin: ['#5a4f42', '#2d3840'], water: ['#183c5b', '#102a4d'] }; const gradient = ctx.createLinearGradient(px, py, px + tile, py + tile); gradient.addColorStop(0, colors[type][0]); gradient.addColorStop(1, colors[type][1]); ctx.fillStyle = gradient; ctx.fillRect(px, py, tile, tile); if (type === 'water') { ctx.strokeStyle = '#5fa6b699'; ctx.lineWidth = 2; for (let line = 14; line < tile; line += 18) { ctx.beginPath(); ctx.moveTo(px + 7, py + line); ctx.quadraticCurveTo(px + tile / 2, py + line - 5, px + tile - 7, py + line); ctx.stroke(); } } if (type === 'forest') { ctx.fillStyle = '#8ce49a77'; for (let i = 0; i < 4; i++) { const tx = px + 13 + ((x * 17 + y * 9 + i * 11) % 36), ty = py + 16 + ((y * 13 + x * 7 + i * 9) % 30); ctx.beginPath(); ctx.moveTo(tx, ty - 11); ctx.lineTo(tx - 8, ty + 6); ctx.lineTo(tx + 8, ty + 6); ctx.closePath(); ctx.fill(); } } if (type === 'ridge') { ctx.strokeStyle = '#c4cfac66'; ctx.lineWidth = 2; for (let i = 0; i < 3; i++) { ctx.beginPath(); ctx.arc(px + tile / 2, py + tile / 2, 10 + i * 7, Math.PI * .1, Math.PI * 1.1); ctx.stroke(); } } if (type === 'ruin') { ctx.strokeStyle = '#ffc76d99'; ctx.lineWidth = 3; ctx.strokeRect(px + 16, py + 15, 28, 28); ctx.beginPath(); ctx.moveTo(px + 16, py + 29); ctx.lineTo(px + 44, py + 29); ctx.stroke(); } ctx.strokeStyle = '#b7edf21c'; ctx.strokeRect(px + .5, py + .5, tile - 1, tile - 1); }
  function draw() { ctx.clearRect(0, 0, canvas.width, canvas.height); for (let y = 0; y < rows; y++) for (let x = 0; x < cols; x++) drawTile(x, y, terrain[y * cols + x]); ctx.fillStyle = '#07101899'; for (let y = 0; y < rows; y++) for (let x = 0; x < cols; x++) if (!visible.has(key(x, y))) ctx.fillRect(x * tile, y * tile, tile, tile); storms.forEach(storm => { if (!visible.has(key(storm.x, storm.y))) return; const px = storm.x * tile + tile / 2, py = storm.y * tile + tile / 2; ctx.fillStyle = '#a98dff35'; ctx.beginPath(); ctx.arc(px, py, 22 + Math.sin(performance.now() / 220) * 3, 0, Math.PI * 2); ctx.fill(); ctx.strokeStyle = '#c1a8ff99'; ctx.stroke(); }); if (visible.has(key(base.x, base.y))) { const px = base.x * tile + tile / 2, py = base.y * tile + tile / 2; ctx.fillStyle = '#75f0dc'; ctx.shadowColor = '#75f0dc'; ctx.shadowBlur = 18; ctx.beginPath(); ctx.arc(px, py, 15, 0, Math.PI * 2); ctx.fill(); ctx.shadowBlur = 0; ctx.fillStyle = '#062022'; ctx.font = 'bold 20px system-ui'; ctx.textAlign = 'center'; ctx.textBaseline = 'middle'; ctx.fillText('⌂', px, py); } targets.forEach(target => { if (!visible.has(key(target.x, target.y)) || target.found) return; const px = target.x * tile + tile / 2, py = target.y * tile + tile / 2; const pulse = 18 + Math.sin(performance.now() / 250) * 3; ctx.strokeStyle = '#ffc76d'; ctx.lineWidth = 2; ctx.shadowColor = '#ffc76d'; ctx.shadowBlur = pulse; ctx.beginPath(); ctx.arc(px, py, 12, 0, Math.PI * 2); ctx.stroke(); ctx.shadowBlur = 0; ctx.fillStyle = '#ffc76d'; ctx.beginPath(); ctx.moveTo(px, py - 9); ctx.lineTo(px + 8, py + 7); ctx.lineTo(px - 8, py + 7); ctx.closePath(); ctx.fill(); }); sentinels.forEach(sentinel => { if (!visible.has(key(sentinel.x, sentinel.y))) return; const px = sentinel.x * tile + tile / 2, py = sentinel.y * tile + tile / 2; ctx.fillStyle = '#ff7f8f'; ctx.shadowColor = '#ff7f8f'; ctx.shadowBlur = 14; ctx.beginPath(); ctx.arc(px, py, 12, 0, Math.PI * 2); ctx.fill(); ctx.shadowBlur = 0; ctx.fillStyle = '#35141e'; ctx.font = 'bold 14px system-ui'; ctx.textAlign = 'center'; ctx.textBaseline = 'middle'; ctx.fillText('!', px, py); }); const px = player.x * tile + tile / 2, py = player.y * tile + tile / 2; ctx.fillStyle = '#d0f780'; ctx.shadowColor = '#d0f780'; ctx.shadowBlur = 17; ctx.beginPath(); ctx.arc(px, py, 15, 0, Math.PI * 2); ctx.fill(); ctx.shadowBlur = 0; ctx.strokeStyle = '#082026'; ctx.lineWidth = 3; ctx.stroke(); ctx.fillStyle = '#082026'; ctx.font = 'bold 18px system-ui'; ctx.textAlign = 'center'; ctx.textBaseline = 'middle'; ctx.fillText('◆', px, py); if (active) animation = requestAnimationFrame(draw); }
  function adjacent(x, y) { return Math.abs(player.x - x) + Math.abs(player.y - y) === 1; }
  function move(dx, dy) { if (!active || energy <= 0) return setStatus('No te queda energía. Termina el turno para recargar.'); const nx = player.x + dx, ny = player.y + dy; if (!terrainPassable(nx, ny)) return setStatus('Ese terreno bloquea el paso.'); if (sentinelAt(nx, ny)) return setStatus('Una patrulla ocupa esa casilla. Elige otra ruta.'); player = { x: nx, y: ny }; energy -= 1; reveal(1); const target = targetAt(nx, ny); if (target && !target.found && visible.has(key(nx, ny))) { target.found = true; discoveries += 1; score += 100; setStatus('Anomalía localizada. Has ganado 100 puntos.'); } else setStatus('Movimiento realizado. Escanea para revelar más terreno.'); if (discoveries === 3 && player.x === base.x && player.y === base.y) finish(true); updateHud(); draw(); }
  function scan() { if (!active || energy < 2) return setStatus('Necesitas 2 unidades de energía para escanear.'); energy -= 2; reveal(2.7); let found = 0; targets.forEach(target => { if (!target.found && Math.hypot(target.x - player.x, target.y - player.y) <= 2.7) { target.found = true; discoveries += 1; found += 1; score += 150; } }); setStatus(found ? `Escaneo completado: ${found} anomalía${found > 1 ? 's' : ''} localizada${found > 1 ? 's' : ''}.` : 'Escaneo completado. No hay anomalías en el radio.'); if (discoveries === 3 && player.x === base.x && player.y === base.y) finish(true); updateHud(); draw(); }
  function endTurn() { if (!active) return; turn += 1; energy = 4; storms = storms.map((storm, index) => ({ x: clamp(storm.x + (index % 2 ? 1 : -1), 1, cols - 2), y: clamp(storm.y + (index % 2 ? -1 : 1), 1, rows - 2) })); sentinels = sentinels.map(sentinel => { const options = [[sentinel.x + Math.sign(player.x - sentinel.x), sentinel.y], [sentinel.x, sentinel.y + Math.sign(player.y - sentinel.y)]]; const choice = options.find(([x, y]) => terrainPassable(x, y) && !stormAt(x, y) && !targetAt(x, y)); return choice ? { x: choice[0], y: choice[1] } : sentinel; }); reveal(1); if (sentinels.some(sentinel => sentinel.x === player.x && sentinel.y === player.y || adjacent(sentinel.x, sentinel.y))) { score = Math.max(0, score - 50); energy = Math.max(1, energy - 1); setStatus('Una patrulla te ha detectado: -50 puntos y -1 energía.'); } else setStatus('Nuevo turno. Las patrullas y la tormenta se han movido.'); updateHud(); draw(); }
  function finish(won) { active = false; cancelAnimationFrame(animation); $('scan').disabled = true; $('end').disabled = true; $('message').hidden = false; $('message').innerHTML = `<p class="eyebrow">${won ? 'MISIÓN COMPLETADA' : 'MISIÓN INTERRUMPIDA'}</p><strong>${won ? 'Cartografía recuperada.' : 'La expedición se queda sin energía.'}</strong><span>${won ? `Has vuelto a la base con ${score} puntos en ${turn} turnos.` : 'Prueba otra ruta, usa los escaneos con más estrategia y evita las patrullas.'}</span><button id="startAgain" type="button" class="primary">Jugar de nuevo</button>`; $('startAgain').addEventListener('click', start); if (won) { const best = Number(localStorage.getItem(bestKey) || 0); if (score > best) localStorage.setItem(bestKey, score); } }
  function start() { makeMap(); turn = 1; energy = 4; score = 0; discoveries = 0; active = true; $('message').hidden = true; updateHud(); setStatus('Misión iniciada. Cada movimiento consume 1 energía.'); draw(); }
  function newMission() { active = false; cancelAnimationFrame(animation); $('message').hidden = false; $('message').innerHTML = '<p class="eyebrow">OPERACIÓN CARTA · MAPA 02</p><strong>Encuentra las tres anomalías.</strong><span>Muévete por las casillas, escanea el terreno y vuelve a la base.</span><button id="start" type="button" class="primary">Iniciar misión</button>'; $('start').addEventListener('click', start); makeMap(); updateHud(); draw(); setStatus('Pulsa iniciar para comenzar.'); }
  canvas.addEventListener('pointerdown', event => { if (!active) return; const rect = canvas.getBoundingClientRect(); const x = Math.floor((event.clientX - rect.left) / rect.width * cols), y = Math.floor((event.clientY - rect.top) / rect.height * rows); if (adjacent(x, y)) move(x - player.x, y - player.y); else setStatus('Selecciona una casilla adyacente.'); });
  document.addEventListener('keydown', event => { const map = { ArrowUp: 'up', w: 'up', W: 'up', ArrowDown: 'down', s: 'down', S: 'down', ArrowLeft: 'left', a: 'left', A: 'left', ArrowRight: 'right', d: 'right', D: 'right' }; if (map[event.key]) { event.preventDefault(); const [dx, dy] = dirs[map[event.key]]; move(dx, dy); } if (event.key === ' ') { event.preventDefault(); scan(); } if (event.key === 'Enter') { event.preventDefault(); endTurn(); } });
  document.querySelectorAll('[data-move]').forEach(button => button.addEventListener('click', () => { const [dx, dy] = dirs[button.dataset.move]; move(dx, dy); })); $('scan').addEventListener('click', scan); $('end').addEventListener('click', endTurn); $('restart').addEventListener('click', newMission); $('start').addEventListener('click', start); newMission();
})();
