(() => {
  const $ = id => document.getElementById(id); const canvas = $('board'); const ctx = canvas.getContext('2d'); const cols = 15, rows = 9, tile = canvas.width / cols; const dirs = { up: [0, -1], down: [0, 1], left: [-1, 0], right: [1, 0] };
  let seed = 1, terrain, visible, base, player, beacons, enemies, stage = 1, energy = 5, credits = 0, score = 0, active = false, animation;
  function rng() { seed = (seed * 1664525 + 1013904223) >>> 0; return seed / 4294967296; }
  function key(x, y) { return `${x},${y}`; } function clamp(value, min, max) { return Math.max(min, Math.min(max, value)); } function adjacent(a, b) { return Math.abs(a.x - b.x) + Math.abs(a.y - b.y) === 1; }
  function terrainPassable(x, y) { return x >= 0 && x < cols && y >= 0 && y < rows && terrain[y * cols + x] !== 'water'; }
  function beaconAt(x, y) { return beacons.find(beacon => beacon.x === x && beacon.y === y); }
  function enemyAt(x, y) { return enemies.find(enemy => enemy.x === x && enemy.y === y); }
  function reveal(radius) { for (let y = 0; y < rows; y++) for (let x = 0; x < cols; x++) if (Math.hypot(x - player.x, y - player.y) <= radius) visible.add(key(x, y)); }
  function createStage() { seed = stage * 733 + 19; terrain = []; visible = new Set(); base = { x: 1, y: rows - 2 }; player = { ...base }; for (let y = 0; y < rows; y++) for (let x = 0; x < cols; x++) { const roll = rng(); terrain.push(roll < .09 ? 'water' : roll < .24 ? 'forest' : roll < .36 ? 'ridge' : roll < .42 ? 'ruin' : 'plain'); } const spots = [{ x: 5, y: 1 }, { x: 11, y: 2 }, { x: 12, y: 7 }, { x: 6, y: 6 }]; beacons = spots.slice(0, stage + 1).map(point => ({ ...point, captured: false })); enemies = [{ x: 13, y: 1 }, { x: 9, y: 4 }, { x: 13, y: 7 }].slice(0, stage + 1); [base, player, ...beacons, ...enemies].forEach(point => terrain[point.y * cols + point.x] = 'plain'); reveal(1.6); updateHud(); draw(); }
  function updateHud() { $('stage').textContent = `${stage} / 3`; $('energy').textContent = energy; $('beacons').textContent = `${beacons.filter(item => item.captured).length} / ${beacons.length}`; $('credits').textContent = credits; $('score').textContent = score; $('scan').disabled = !active || energy < 2; $('end').disabled = !active; $('upgrade').disabled = active ? credits < 2 : credits < 2; }
  function drawTile(x, y, type) { const px = x * tile, py = y * tile; const colors = { plain: ['#172c4b', '#101c37'], forest: ['#1d4e4f', '#112c3f'], ridge: ['#4d4a60', '#292d4a'], ruin: ['#66516a', '#342f4e'], water: ['#183d69', '#112951'] }; const gradient = ctx.createLinearGradient(px, py, px + tile, py + tile); gradient.addColorStop(0, colors[type][0]); gradient.addColorStop(1, colors[type][1]); ctx.fillStyle = gradient; ctx.fillRect(px, py, tile, tile); if (type === 'water') { ctx.strokeStyle = '#77b9ff66'; ctx.lineWidth = 2; for (let i = 14; i < tile; i += 16) { ctx.beginPath(); ctx.moveTo(px + 8, py + i); ctx.quadraticCurveTo(px + tile / 2, py + i - 5, px + tile - 8, py + i); ctx.stroke(); } } if (type === 'forest') { ctx.fillStyle = '#72e0c277'; for (let i = 0; i < 4; i++) { const tx = px + 13 + ((x * 13 + y * 7 + i * 12) % 38), ty = py + 15 + ((y * 11 + x * 9 + i * 8) % 33); ctx.beginPath(); ctx.moveTo(tx, ty - 12); ctx.lineTo(tx - 8, ty + 7); ctx.lineTo(tx + 8, ty + 7); ctx.closePath(); ctx.fill(); } } if (type === 'ridge') { ctx.strokeStyle = '#e7d8ff66'; ctx.lineWidth = 2; for (let i = 0; i < 3; i++) { ctx.beginPath(); ctx.arc(px + tile / 2, py + tile / 2, 10 + i * 7, .15 * Math.PI, 1.15 * Math.PI); ctx.stroke(); } } if (type === 'ruin') { ctx.strokeStyle = '#ffc76d99'; ctx.lineWidth = 3; ctx.strokeRect(px + 16, py + 15, 30, 29); ctx.beginPath(); ctx.moveTo(px + 16, py + 29); ctx.lineTo(px + 46, py + 29); ctx.stroke(); } ctx.strokeStyle = '#a8dcff1e'; ctx.strokeRect(px + .5, py + .5, tile - 1, tile - 1); }
  function draw() { ctx.clearRect(0, 0, canvas.width, canvas.height); for (let y = 0; y < rows; y++) for (let x = 0; x < cols; x++) drawTile(x, y, terrain[y * cols + x]); ctx.fillStyle = '#060b18aa'; for (let y = 0; y < rows; y++) for (let x = 0; x < cols; x++) if (!visible.has(key(x, y))) ctx.fillRect(x * tile, y * tile, tile, tile); beacons.forEach(beacon => { if (!visible.has(key(beacon.x, beacon.y)) || beacon.captured) return; const px = beacon.x * tile + tile / 2, py = beacon.y * tile + tile / 2, pulse = 17 + Math.sin(performance.now() / 230) * 3; ctx.strokeStyle = '#ffc76d'; ctx.lineWidth = 2; ctx.shadowColor = '#ffc76d'; ctx.shadowBlur = pulse; ctx.beginPath(); ctx.arc(px, py, 12, 0, Math.PI * 2); ctx.stroke(); ctx.shadowBlur = 0; ctx.fillStyle = '#ffc76d'; ctx.beginPath(); ctx.moveTo(px, py - 9); ctx.lineTo(px + 8, py + 7); ctx.lineTo(px - 8, py + 7); ctx.closePath(); ctx.fill(); }); enemies.forEach(enemy => { if (!visible.has(key(enemy.x, enemy.y))) return; const px = enemy.x * tile + tile / 2, py = enemy.y * tile + tile / 2; ctx.fillStyle = '#ff7c98'; ctx.shadowColor = '#ff7c98'; ctx.shadowBlur = 14; ctx.beginPath(); ctx.moveTo(px, py - 14); ctx.lineTo(px + 13, py + 11); ctx.lineTo(px - 13, py + 11); ctx.closePath(); ctx.fill(); ctx.shadowBlur = 0; ctx.fillStyle = '#35131d'; ctx.font = 'bold 14px system-ui'; ctx.textAlign = 'center'; ctx.textBaseline = 'middle'; ctx.fillText('!', px, py + 2); }); if (visible.has(key(base.x, base.y))) { const px = base.x * tile + tile / 2, py = base.y * tile + tile / 2; ctx.fillStyle = '#73e6ff'; ctx.shadowColor = '#73e6ff'; ctx.shadowBlur = 18; ctx.beginPath(); ctx.arc(px, py, 16, 0, Math.PI * 2); ctx.fill(); ctx.shadowBlur = 0; ctx.fillStyle = '#071a24'; ctx.font = 'bold 20px system-ui'; ctx.textAlign = 'center'; ctx.textBaseline = 'middle'; ctx.fillText('⌂', px, py); } const px = player.x * tile + tile / 2, py = player.y * tile + tile / 2; ctx.fillStyle = '#d8f77d'; ctx.shadowColor = '#d8f77d'; ctx.shadowBlur = 17; ctx.beginPath(); ctx.arc(px, py, 15, 0, Math.PI * 2); ctx.fill(); ctx.shadowBlur = 0; ctx.strokeStyle = '#0c1830'; ctx.lineWidth = 3; ctx.stroke(); ctx.fillStyle = '#0c1830'; ctx.font = 'bold 18px system-ui'; ctx.fillText('◆', px, py); if (active) animation = requestAnimationFrame(draw); }
  function setStatus(message) { $('status').textContent = message; }
  function move(dx, dy) { if (!active || energy <= 0) return setStatus('No queda energía. Termina el turno para recargar.'); const next = { x: player.x + dx, y: player.y + dy }; if (!terrainPassable(next.x, next.y)) return setStatus('Ese terreno bloquea el paso.'); if (enemyAt(next.x, next.y)) return setStatus('Una unidad enemiga ocupa esa casilla.'); player = next; energy -= 1; reveal(1.3); const beacon = beaconAt(player.x, player.y); if (beacon && !beacon.captured) { beacon.captured = true; score += 120; setStatus('Baliza capturada: +120 puntos.'); } else setStatus('Movimiento realizado. Escanea zonas ocultas para planificar.'); updateHud(); draw(); checkComplete(); }
  function scan() { if (!active || energy < 2) return setStatus('Necesitas 2 unidades de energía para escanear.'); energy -= 2; reveal(2.8); score += 10; setStatus('Escaneo completado. La niebla se ha reducido.'); updateHud(); draw(); }
  function endTurn() { if (!active) return; energy = Math.min(5 + (credits >= 2 ? 1 : 0), energy + 5); enemies = enemies.map(enemy => { const options = [[enemy.x + Math.sign(player.x - enemy.x), enemy.y], [enemy.x, enemy.y + Math.sign(player.y - enemy.y)]]; const choice = options.find(([x, y]) => terrainPassable(x, y) && !enemyAt(x, y) && !beaconAt(x, y)); return choice ? { x: choice[0], y: choice[1] } : enemy; }); if (enemies.some(enemy => adjacent(enemy, player))) { energy = Math.max(0, energy - 1); score = Math.max(0, score - 60); setStatus('Una unidad enemiga te ha interceptado: -60 puntos.'); } else setStatus('Nuevo turno. Las unidades enemigas se han movido.'); if (energy <= 0) return finish(false); updateHud(); draw(); }
  function checkComplete() { const captured = beacons.every(beacon => beacon.captured); if (captured && player.x === base.x && player.y === base.y) completeStage(); }
  function completeStage() { active = false; cancelAnimationFrame(animation); credits += 2; score += 250; updateHud(); $('message').hidden = false; if (stage < 3) { $('message').innerHTML = `<p class="eyebrow">MAPA ${stage} COMPLETADO</p><strong>La ruta está asegurada.</strong><span>Has conseguido 2 créditos. Puedes mejorar el escáner antes de avanzar al siguiente mapa.</span><button id="next" type="button" class="primary">Siguiente mapa</button>`; $('next').addEventListener('click', () => { stage += 1; energy = 5; createStage(); active = true; $('message').hidden = true; updateHud(); setStatus('Nuevo mapa. La dificultad ha aumentado.'); draw(); }); } else finish(true); }
  function upgrade() { if (active || credits < 2) return; credits -= 2; energy = Math.min(6, energy + 1); setStatus('Equipo mejorado: recibes una reserva extra de energía.'); updateHud(); }
  function finish(won) { active = false; cancelAnimationFrame(animation); $('scan').disabled = true; $('end').disabled = true; $('upgrade').disabled = true; $('message').hidden = false; $('message').innerHTML = `<p class="eyebrow">${won ? 'CAMPAÑA COMPLETADA' : 'SEÑAL PERDIDA'}</p><strong>${won ? 'Atlas recuperado.' : 'La expedición ha fallado.'}</strong><span>${won ? `Has superado los tres mapas con ${score} puntos.` : 'Planifica mejor los escaneos, usa las mejoras y evita las unidades enemigas.'}</span><button id="again" type="button" class="primary">Jugar de nuevo</button>`; $('again').addEventListener('click', newCampaign); }
  function startCampaign() { stage = 1; credits = 0; score = 0; energy = 5; active = true; $('message').hidden = true; createStage(); setStatus('Campaña iniciada. Captura todas las balizas y vuelve a la base.'); updateHud(); draw(); }
  function newCampaign() { active = false; cancelAnimationFrame(animation); stage = 1; credits = 0; score = 0; energy = 5; createStage(); $('message').hidden = false; $('message').innerHTML = '<p class="eyebrow">OPERACIÓN ATLAS · TRES MAPAS</p><strong>Recupera la cartografía.</strong><span>Completa tres mapas, captura las balizas y vuelve a la base.</span><button id="startAgain" type="button" class="primary">Iniciar campaña</button>'; $('startAgain').addEventListener('click', startCampaign); updateHud(); setStatus('Pulsa iniciar para comenzar.'); }
  canvas.addEventListener('pointerdown', event => { if (!active) return; const rect = canvas.getBoundingClientRect(); const x = Math.floor((event.clientX - rect.left) / rect.width * cols), y = Math.floor((event.clientY - rect.top) / rect.height * rows); if (adjacent(player, { x, y })) move(x - player.x, y - player.y); else setStatus('Selecciona una casilla adyacente.'); });
  document.addEventListener('keydown', event => { const map = { ArrowUp: 'up', w: 'up', W: 'up', ArrowDown: 'down', s: 'down', S: 'down', ArrowLeft: 'left', a: 'left', A: 'left', ArrowRight: 'right', d: 'right', D: 'right' }; if (map[event.key]) { event.preventDefault(); const [dx, dy] = dirs[map[event.key]]; move(dx, dy); } if (event.key === ' ') { event.preventDefault(); scan(); } if (event.key === 'Enter') { event.preventDefault(); endTurn(); } });
  document.querySelectorAll('[data-move]').forEach(button => button.addEventListener('click', () => { const [dx, dy] = dirs[button.dataset.move]; move(dx, dy); })); $('scan').addEventListener('click', scan); $('end').addEventListener('click', endTurn); $('upgrade').addEventListener('click', upgrade); $('restart').addEventListener('click', newCampaign); $('start').addEventListener('click', startCampaign); newCampaign();
})();
