const $ = id => document.getElementById(id);
const canvas = $('canvas');
const missions = [
  { name: 'Marisma de Levante', target: 5, time: 72, seed: 17, terrain: 'water' },
  { name: 'Lomas del Viento', target: 6, time: 80, seed: 43, terrain: 'ridge' },
  { name: 'Ruinas del Norte', target: 7, time: 88, seed: 91, terrain: 'ruins' }
];
const state = { mission: 0, score: 0, battery: 100, running: false, paused: false, over: false, time: 0, collected: 0, player: { x: .5, y: .55 }, targets: [], hazards: [], particles: [], pulse: 0, seed: 0, last: 0, controls: new Set(), raf: 0, transition: 0 };
function seeded(seed) { let value = seed >>> 0; return () => { value = (value * 1664525 + 1013904223) >>> 0; return value / 4294967296; }; }
function resize() { const rect = canvas.getBoundingClientRect(); const dpr = Math.min(window.devicePixelRatio || 1, 2); canvas.width = Math.max(320, rect.width) * dpr; canvas.height = Math.max(250, rect.width * .5625) * dpr; }
function setStatus(text) { $('status').textContent = text; }
function updateHud() { const mission = missions[state.mission]; $('mission').textContent = mission ? (state.mission + 1) + ' / ' + missions.length + ' · ' + mission.name : 'Completada'; $('score').textContent = state.score; $('battery').textContent = Math.max(0, Math.round(state.battery)) + '%'; $('samples').textContent = state.collected + ' / ' + (mission ? mission.target : 0); }
function beginMission(index) {
  const mission = missions[index]; const random = seeded(mission.seed); state.mission = index; state.collected = 0; state.time = mission.time; state.battery = Math.min(100, state.battery + 25); state.player = { x: .5, y: .56 }; state.targets = []; state.hazards = []; state.particles = []; state.pulse = 0;
  for (let i = 0; i < mission.target; i += 1) state.targets.push({ x: .1 + random() * .8, y: .12 + random() * .72, found: false, revealed: 0, phase: random() * 6 });
  const hazards = 4 + index;
  for (let i = 0; i < hazards; i += 1) state.hazards.push({ x: .12 + random() * .76, y: .12 + random() * .72, r: .035 + random() * .045, phase: random() * 6, hit: 0 });
  updateHud(); setStatus('Zona activa. Recoge todos los objetivos y administra la batería.'); draw();
}
function startCampaign() { state.transition += 1; state.score = 0; state.battery = 100; state.running = true; state.paused = false; state.over = false; $('overlay').hidden = true; $('pause').textContent = 'Pausar'; beginMission(0); state.last = performance.now(); cancelAnimationFrame(state.raf); state.raf = requestAnimationFrame(loop); }
function finishMission() { state.running = false; state.score += Math.round(state.time * 4) + Math.round(state.battery); updateHud(); setStatus('Zona completada. Preparando el siguiente sector…'); const transition = ++state.transition; setTimeout(() => { if (transition !== state.transition) return; if (state.mission + 1 < missions.length) { state.running = true; beginMission(state.mission + 1); } else completeCampaign(); }, 850); }
function completeCampaign() { state.running = false; state.over = true; $('overlayTitle').textContent = 'Campaña completada'; $('overlayText').textContent = 'Has cartografiado las tres zonas con ' + state.score + ' puntos.'; $('start').textContent = 'Jugar de nuevo'; $('overlay').hidden = false; setStatus('Buen trabajo: todos los sectores están documentados.'); draw(); }
function gameOver(reason) { state.running = false; state.over = true; $('overlayTitle').textContent = 'Misión fallida'; $('overlayText').textContent = reason + ' Puntuación: ' + state.score + '.'; $('start').textContent = 'Reintentar campaña'; $('overlay').hidden = false; setStatus('La campaña se puede reiniciar en cualquier momento.'); draw(); }
function pulse() { if (!state.running || state.paused || state.battery < 12) return; state.battery -= 12; state.pulse = 1; state.targets.forEach(target => { const distance = Math.hypot(target.x - state.player.x, target.y - state.player.y); if (distance < .25) target.revealed = 4; }); setStatus('Pulso emitido: las muestras cercanas quedan resaltadas.'); updateHud(); }
function inputVector() { let x = 0; let y = 0; if (state.controls.has('left') || state.controls.has('a')) x -= 1; if (state.controls.has('right') || state.controls.has('d')) x += 1; if (state.controls.has('up') || state.controls.has('w')) y -= 1; if (state.controls.has('down') || state.controls.has('s')) y += 1; const length = Math.hypot(x, y) || 1; return { x: x / length, y: y / length, moving: Boolean(x || y) }; }
function update(dt) {
  if (!state.running || state.paused) return;
  const vector = inputVector(); const boosting = state.controls.has('boost') && state.battery > 3; const speed = boosting ? .34 : .22;
  state.player.x = Math.max(.055, Math.min(.945, state.player.x + vector.x * speed * dt)); state.player.y = Math.max(.08, Math.min(.92, state.player.y + vector.y * speed * dt)); state.battery -= dt * (vector.moving ? (boosting ? 9 : 3.8) : 1.1); if (boosting) state.controls.delete('boost');
  state.time -= dt; state.pulse = Math.max(0, state.pulse - dt); state.targets.forEach(target => { target.revealed = Math.max(0, target.revealed - dt); if (!target.found && Math.hypot(target.x - state.player.x, target.y - state.player.y) < .045) { target.found = true; state.collected += 1; state.score += 100; burst(target.x, target.y, '#ffc66e'); setStatus('Muestra localizada. Sigue buscando el siguiente punto.'); } });
  state.hazards.forEach(hazard => { hazard.phase += dt * 2; hazard.hit = Math.max(0, hazard.hit - dt); if (Math.hypot(hazard.x - state.player.x, hazard.y - state.player.y) < hazard.r + .025 && hazard.hit === 0) { hazard.hit = 1.8; state.battery -= 13; state.score = Math.max(0, state.score - 20); burst(state.player.x, state.player.y, '#ff718d'); setStatus('Impacto en zona peligrosa: batería -13%.'); } });
  state.particles.forEach(particle => { particle.life -= dt; particle.x += particle.vx * dt; particle.y += particle.vy * dt; }); state.particles = state.particles.filter(particle => particle.life > 0);
  if (state.collected >= missions[state.mission].target) finishMission(); else if (state.time <= 0) gameOver('Se agotó el tiempo de prospección.'); else if (state.battery <= 0) gameOver('El rover se quedó sin batería.');
  updateHud();
}
function burst(x, y, color) { for (let i = 0; i < 14; i += 1) { const angle = i / 14 * Math.PI * 2; state.particles.push({ x, y, vx: Math.cos(angle) * .08, vy: Math.sin(angle) * .08, life: .75, color }); } }
function draw() {
  const dpr = Math.min(window.devicePixelRatio || 1, 2); const width = canvas.width / dpr; const height = canvas.height / dpr; const context = canvas.getContext('2d'); context.setTransform(dpr, 0, 0, dpr, 0, 0); context.clearRect(0, 0, width, height);
  const mission = missions[state.mission] || missions[0]; const time = performance.now() / 1000;
  const background = context.createLinearGradient(0, 0, width, height); background.addColorStop(0, mission.terrain === 'water' ? '#123d4a' : '#172c3c'); background.addColorStop(1, mission.terrain === 'ruins' ? '#412d32' : '#0b1d2c'); context.fillStyle = background; context.fillRect(0, 0, width, height);
  context.strokeStyle = '#ffffff12'; context.lineWidth = 1; for (let x = 0; x < 12; x += 1) { context.beginPath(); context.moveTo(x * width / 11, 0); context.lineTo(x * width / 11, height); context.stroke(); } for (let y = 0; y < 8; y += 1) { context.beginPath(); context.moveTo(0, y * height / 7); context.lineTo(width, y * height / 7); context.stroke(); }
  context.strokeStyle = mission.terrain === 'water' ? '#72d7d055' : '#d5b57c35'; context.lineWidth = 10; context.beginPath(); context.moveTo(width * .02, height * .82); context.bezierCurveTo(width * .3, height * .5, width * .6, height * .85, width * .98, height * .23); context.stroke();
  context.strokeStyle = '#ffffff18'; context.lineWidth = 2; for (let row = 0; row < 6; row += 1) { context.beginPath(); for (let x = 0; x <= width; x += 16) { const y = height * (.13 + row * .15) + Math.sin(x / 80 + row + time * .12) * 7; x ? context.lineTo(x, y) : context.moveTo(x, y); } context.stroke(); }
  if (mission.terrain === 'ruins') { context.fillStyle = '#f2c17b34'; for (let i = 0; i < 12; i += 1) { const x = (i * 97 % 900) / 900 * width; const y = (i * 43 % 530) / 530 * height; context.fillRect(x, y, 13 + i % 3 * 8, 7); } }
  state.hazards.forEach(hazard => { const x = hazard.x * width; const y = hazard.y * height; const radius = hazard.r * width * (1 + Math.sin(hazard.phase) * .08); const glow = context.createRadialGradient(x, y, 2, x, y, radius * 2.3); glow.addColorStop(0, '#ff718d88'); glow.addColorStop(1, '#ff718d00'); context.fillStyle = glow; context.beginPath(); context.arc(x, y, radius * 2.3, 0, Math.PI * 2); context.fill(); context.strokeStyle = '#ff718d99'; context.setLineDash([5, 7]); context.beginPath(); context.arc(x, y, radius, 0, Math.PI * 2); context.stroke(); context.setLineDash([]); });
  state.targets.forEach(target => { if (target.found) return; const visible = target.revealed > 0 || Math.hypot(target.x - state.player.x, target.y - state.player.y) < .12; const x = target.x * width; const y = target.y * height; const pulse = 1 + Math.sin(time * 4 + target.phase) * .12; context.save(); context.globalAlpha = visible ? 1 : .38; context.strokeStyle = '#ffc66e77'; context.lineWidth = 2; context.beginPath(); context.arc(x, y, 17 * pulse, 0, Math.PI * 2); context.stroke(); context.fillStyle = '#ffc66e'; context.beginPath(); context.moveTo(x, y - 9); context.lineTo(x + 8, y + 5); context.lineTo(x, y + 11); context.lineTo(x - 8, y + 5); context.closePath(); context.fill(); context.restore(); });
  state.particles.forEach(particle => { context.globalAlpha = Math.max(0, particle.life); context.fillStyle = particle.color; context.beginPath(); context.arc(particle.x * width, particle.y * height, 3 + particle.life * 3, 0, Math.PI * 2); context.fill(); }); context.globalAlpha = 1;
  if (state.pulse > 0) { context.strokeStyle = '#72e0c1aa'; context.lineWidth = 3; context.beginPath(); context.arc(state.player.x * width, state.player.y * height, (1 - state.pulse) * width * .3, 0, Math.PI * 2); context.stroke(); }
  const px = state.player.x * width; const py = state.player.y * height; context.save(); context.translate(px, py); context.rotate(Math.atan2(inputVector().y, inputVector().x) + Math.PI / 2); context.shadowColor = '#72e0c1'; context.shadowBlur = 18; context.fillStyle = '#72e0c1'; context.beginPath(); context.moveTo(0, -15); context.lineTo(12, 11); context.lineTo(0, 7); context.lineTo(-12, 11); context.closePath(); context.fill(); context.shadowBlur = 0; context.fillStyle = '#08202a'; context.beginPath(); context.arc(0, -2, 4, 0, Math.PI * 2); context.fill(); context.restore();
  context.fillStyle = '#ffffffb5'; context.font = '12px system-ui'; context.fillText('N', 16, 22); context.fillText('Tiempo ' + Math.max(0, Math.ceil(state.time)) + ' s', width - 95, 22);
}
function loop(now) { const dt = Math.min(.04, (now - state.last) / 1000 || 0); state.last = now; update(dt); draw(); if (state.running || !state.over) state.raf = requestAnimationFrame(loop); }
function setControl(name, active) { if (active) state.controls.add(name); else state.controls.delete(name); }
document.querySelectorAll('[data-key]').forEach(button => { const key = button.dataset.key; const on = event => { event.preventDefault(); button.classList.add('active'); setControl(key, true); }; const off = event => { event.preventDefault(); button.classList.remove('active'); setControl(key, false); }; button.addEventListener('pointerdown', on); button.addEventListener('pointerup', off); button.addEventListener('pointercancel', off); button.addEventListener('pointerleave', off); });
window.addEventListener('keydown', event => { const key = event.key.toLowerCase(); if (['arrowup', 'arrowdown', 'arrowleft', 'arrowright', 'w', 'a', 's', 'd'].includes(key)) { event.preventDefault(); setControl(key.replace('arrow', ''), true); } if (key === 'shift') setControl('boost', true); if (key === ' ') { event.preventDefault(); pulse(); } if (key === 'p') togglePause(); });
window.addEventListener('keyup', event => { const key = event.key.toLowerCase(); if (['up', 'down', 'left', 'right', 'w', 'a', 's', 'd'].includes(key.replace('arrow', ''))) setControl(key.replace('arrow', ''), false); if (key === 'shift') setControl('boost', false); });
function togglePause() { if (!state.running) return; state.paused = !state.paused; $('pause').textContent = state.paused ? 'Continuar' : 'Pausar'; setStatus(state.paused ? 'Pausa. Pulsa Continuar para volver a la zona.' : 'Misión reanudada.'); }
$('start').addEventListener('click', startCampaign); $('pulse').addEventListener('click', pulse); $('pause').addEventListener('click', togglePause); $('restart').addEventListener('click', startCampaign); window.addEventListener('resize', () => { resize(); draw(); }); resize(); beginMission(0); state.over = true; draw();
