const $ = id => document.getElementById(id);
const COLS = 9;
const ROWS = 6;
const scenarios = [
  { name: 'Valle del Ámbar', objective: 7, turns: 12, seed: 12, palette: ['#1b4d50', '#0d273b'] },
  { name: 'Meseta de Bruma', objective: 8, turns: 14, seed: 46, palette: ['#344b70', '#111f3a'] },
  { name: 'Cuenca de las Ruinas', objective: 9, turns: 15, seed: 88, palette: ['#533b55', '#241e36'] }
];
const state = { scenario: 0, turn: 1, energy: 7, intel: 0, score: 0, running: false, paused: false, over: true, selected: { c: 4, r: 3 }, player: { c: 4, r: 3 }, map: [], revealed: new Set(), claimed: new Set(), enemy: new Set(), surveyed: new Set(), particles: [], transition: 0, last: 0, raf: 0 };
function rng(seed) { let value = seed >>> 0; return () => { value = (value * 1664525 + 1013904223) >>> 0; return value / 4294967296; }; }
function key(c, r) { return c + ',' + r; }
function parseKey(value) { const parts = value.split(',').map(Number); return { c: parts[0], r: parts[1] }; }
function neighbors(cell) { const even = cell.r % 2 === 0; const directions = even ? [[1,0],[0,-1],[-1,-1],[-1,0],[-1,1],[0,1]] : [[1,0],[1,-1],[0,-1],[-1,0],[0,1],[1,1]]; return directions.map(pair => ({ c: cell.c + pair[0], r: cell.r + pair[1] })).filter(item => item.c >= 0 && item.c < COLS && item.r >= 0 && item.r < ROWS); }
function makeMap(seed) { const random = rng(seed); const terrains = ['plain', 'forest', 'ridge', 'water', 'ruin']; return Array.from({ length: COLS * ROWS }, (_, index) => { const c = index % COLS; const r = Math.floor(index / COLS); const roll = random(); return { c, r, terrain: roll < .14 ? 'water' : roll < .34 ? 'forest' : roll < .52 ? 'ridge' : roll < .66 ? 'ruin' : 'plain', resource: Math.round(random() * 3), phase: random() * 6 }; }); }
function getCell(c, r) { return state.map.find(cell => cell.c === c && cell.r === r); }
function setStatus(text) { $('status').textContent = text; }
function revealAround(cell, radius) { state.map.forEach(item => { if (Math.abs(item.c - cell.c) + Math.abs(item.r - cell.r) <= radius + 1) state.revealed.add(key(item.c, item.r)); }); }
function updateHud() { const scenario = scenarios[state.scenario]; $('mission').textContent = state.scenario + 1 + ' / ' + scenarios.length + ' · ' + scenario.name; $('turn').textContent = state.turn + ' / ' + scenario.turns; $('energy').textContent = state.energy; $('territory').textContent = state.claimed.size + ' / ' + scenario.objective; }
function beginScenario(index) { state.scenario = index; state.turn = 1; state.energy = 7; state.intel = 0; state.map = makeMap(scenarios[index].seed); state.revealed = new Set(); state.claimed = new Set([key(4, 3)]); state.enemy = new Set(); state.surveyed = new Set(); state.player = { c: 4, r: 3 }; state.selected = { c: 4, r: 3 }; state.particles = []; revealAround(state.player, 1); updateHud(); setStatus('Selecciona un hexágono vecino para moverte o explora el territorio.'); draw(); }
function startCampaign() { state.transition += 1; state.score = 0; state.running = true; state.paused = false; state.over = false; $('overlay').hidden = true; $('pause').textContent = 'Pausar'; beginScenario(0); state.last = performance.now(); cancelAnimationFrame(state.raf); state.raf = requestAnimationFrame(loop); }
function completeScenario() { state.running = false; state.score += state.energy * 10 + state.intel; setStatus('Sector asegurado. Preparando la siguiente frontera…'); const transition = ++state.transition; setTimeout(() => { if (transition !== state.transition) return; if (state.scenario + 1 < scenarios.length) { state.running = true; beginScenario(state.scenario + 1); } else finishCampaign(); }, 850); }
function finishCampaign() { state.running = false; state.over = true; $('overlayTitle').textContent = 'Frontera cartografiada'; $('overlayText').textContent = 'Has completado los tres sectores con ' + state.score + ' puntos de exploración.'; $('start').textContent = 'Jugar de nuevo'; $('overlay').hidden = false; setStatus('Campaña completada: el atlas está actualizado.'); draw(); }
function failCampaign(reason) { state.running = false; state.over = true; $('overlayTitle').textContent = 'Expedición detenida'; $('overlayText').textContent = reason + ' Puntuación: ' + state.score + '.'; $('start').textContent = 'Reintentar campaña'; $('overlay').hidden = false; setStatus('Puedes reiniciar la expedición.'); draw(); }
function selectedCell() { return getCell(state.selected.c, state.selected.r); }
function adjacent(a, b) { return neighbors(a).some(item => item.c === b.c && item.r === b.r); }
function survey() { if (!state.running || state.paused || state.energy < 1) return; const cell = selectedCell(); if (!cell || !state.revealed.has(key(cell.c, cell.r))) { setStatus('Ese hexágono está oculto. Explora una zona vecina primero.'); return; } state.energy -= 1; state.intel += 1 + cell.resource; state.surveyed.add(key(cell.c, cell.r)); revealAround(cell, 1); state.score += 8 + cell.resource * 3; burst(cell, '#70e2d0'); setStatus('Terreno explorado: +' + (1 + cell.resource) + ' inteligencia.'); updateHud(); }
function claim() { if (!state.running || state.paused || state.energy < 1) return; const cell = selectedCell(); if (!cell || !state.revealed.has(key(cell.c, cell.r)) || !adjacent(state.player, cell) || cell.terrain === 'water' || state.enemy.has(key(cell.c, cell.r))) { setStatus('Solo puedes fundar en un hexágono vecino, descubierto y no inundado.'); return; } state.energy -= 1; state.claimed.add(key(cell.c, cell.r)); state.player = { c: cell.c, r: cell.r }; state.score += 20 + cell.resource * 4; revealAround(cell, 1); burst(cell, '#ffd272'); setStatus('Campamento fundado. Elige el siguiente sector.'); updateHud(); if (state.claimed.size >= scenarios[state.scenario].objective) completeScenario(); }
function enemyTurn() { const candidates = state.map.filter(cell => state.revealed.has(key(cell.c, cell.r)) && !state.claimed.has(key(cell.c, cell.r)) && !state.enemy.has(key(cell.c, cell.r)) && cell.terrain !== 'water'); candidates.sort((a, b) => Math.abs(a.c - state.player.c) + Math.abs(a.r - state.player.r) - (Math.abs(b.c - state.player.c) + Math.abs(b.r - state.player.r))); if (candidates[0]) { state.enemy.add(key(candidates[0].c, candidates[0].r)); burst(candidates[0], '#ff778f'); } }
function endTurn() { if (!state.running || state.paused) return; enemyTurn(); state.turn += 1; state.energy = Math.min(7, state.energy + 2); state.score += 3; updateHud(); setStatus('La frontera rival ha avanzado. Tu energía se ha recuperado.'); if (state.turn > scenarios[state.scenario].turns) failCampaign('Se agotó el límite de turnos.'); }
function center(cell, width, height) { const radius = Math.min(width / 12.7, height / 8.4); const left = (width - (COLS * radius * 1.55)) / 2 + radius; const top = radius * .9; return [left + cell.c * radius * 1.55 + (cell.r % 2 ? radius * .78 : 0), top + cell.r * radius * 1.42]; }
function hex(context, x, y, radius) { context.beginPath(); for (let i = 0; i < 6; i += 1) { const angle = Math.PI / 6 + i * Math.PI / 3; const px = x + Math.cos(angle) * radius; const py = y + Math.sin(angle) * radius; i ? context.lineTo(px, py) : context.moveTo(px, py); } context.closePath(); }
function cellAt(x, y, width, height) { let best = null; const radius = Math.min(width / 12.7, height / 8.4); state.map.forEach(cell => { const point = center(cell, width, height); const distance = Math.hypot(point[0] - x, point[1] - y); if (distance < radius && (!best || distance < best.distance)) best = { cell, distance }; }); return best && best.cell; }
function draw() { const dpr = Math.min(window.devicePixelRatio || 1, 2); const canvas = $('canvas'); const width = canvas.width / dpr; const height = canvas.height / dpr; const context = canvas.getContext('2d'); context.setTransform(dpr, 0, 0, dpr, 0, 0); context.clearRect(0, 0, width, height); const palette = scenarios[state.scenario].palette; const background = context.createLinearGradient(0, 0, width, height); background.addColorStop(0, palette[0]); background.addColorStop(1, palette[1]); context.fillStyle = background; context.fillRect(0, 0, width, height); const radius = Math.min(width / 12.7, height / 8.4); const colors = { plain: '#49725f', forest: '#275a55', ridge: '#665c76', water: '#244d75', ruin: '#806047' }; state.map.forEach(cell => { const point = center(cell, width, height); const cellKey = key(cell.c, cell.r); const revealed = state.revealed.has(cellKey); const selected = state.selected.c === cell.c && state.selected.r === cell.r; hex(context, point[0], point[1], radius * .9); context.fillStyle = revealed ? colors[cell.terrain] : '#0b1b2c'; context.globalAlpha = revealed ? .94 : .86; context.fill(); context.globalAlpha = 1; context.strokeStyle = selected ? '#ffd272' : state.claimed.has(cellKey) ? '#70e2d0' : state.enemy.has(cellKey) ? '#ff778f' : '#b2d0df33'; context.lineWidth = selected ? 3 : 1.2; context.stroke(); if (revealed && cell.resource > 0) { context.fillStyle = cell.terrain === 'ruin' ? '#ffd272' : '#a8e7c0'; context.beginPath(); context.arc(point[0], point[1] - 2, 3 + cell.resource, 0, Math.PI * 2); context.fill(); } if (state.surveyed.has(cellKey)) { context.strokeStyle = '#70e2d0aa'; context.setLineDash([3, 3]); context.beginPath(); context.arc(point[0], point[1], radius * .63, 0, Math.PI * 2); context.stroke(); context.setLineDash([]); } if (state.enemy.has(cellKey)) { context.fillStyle = '#ff778f'; context.beginPath(); context.moveTo(point[0], point[1] + 10); context.lineTo(point[0] - 8, point[1] - 5); context.lineTo(point[0] + 8, point[1] - 5); context.closePath(); context.fill(); } }); const player = center(state.player, width, height); context.save(); context.translate(player[0], player[1]); context.shadowColor = '#70e2d0'; context.shadowBlur = 18; context.fillStyle = '#70e2d0'; context.beginPath(); context.arc(0, 0, radius * .3, 0, Math.PI * 2); context.fill(); context.shadowBlur = 0; context.fillStyle = '#0b2331'; context.beginPath(); context.arc(0, 0, radius * .12, 0, Math.PI * 2); context.fill(); context.restore(); state.particles.forEach(particle => { context.globalAlpha = Math.max(0, particle.life); const point = center(particle.cell, width, height); context.fillStyle = particle.color; context.beginPath(); context.arc(point[0] + particle.x, point[1] + particle.y, 3 + particle.life * 3, 0, Math.PI * 2); context.fill(); }); context.globalAlpha = 1; context.fillStyle = '#ffffffb7'; context.font = '12px system-ui'; context.fillText('N', 14, 21); context.fillText('INT ' + state.intel, width - 55, 21); }
function burst(cell, color) { for (let i = 0; i < 12; i += 1) { const angle = i / 12 * Math.PI * 2; state.particles.push({ cell: { c: cell.c, r: cell.r }, x: 0, y: 0, vx: Math.cos(angle) * 16, vy: Math.sin(angle) * 16, life: .7, color }); } }
function loop(now) { const dt = Math.min(.04, (now - state.last) / 1000 || 0); state.last = now; state.particles.forEach(particle => { particle.life -= dt; particle.x += particle.vx * dt; particle.y += particle.vy * dt; }); state.particles = state.particles.filter(particle => particle.life > 0); draw(); if (state.running || !state.over) state.raf = requestAnimationFrame(loop); }
function resize() { const canvas = $('canvas'); const rect = canvas.getBoundingClientRect(); const dpr = Math.min(window.devicePixelRatio || 1, 2); canvas.width = Math.max(320, rect.width) * dpr; canvas.height = Math.max(250, rect.width * .625) * dpr; draw(); }
function togglePause() { if (!state.running) return; state.paused = !state.paused; $('pause').textContent = state.paused ? 'Continuar' : 'Pausar'; setStatus(state.paused ? 'Pausa: las fronteras no avanzan.' : 'Campaña reanudada.'); }
$('canvas').addEventListener('pointerdown', event => { if (!state.running || state.paused) return; const rect = $('canvas').getBoundingClientRect(); const cell = cellAt(event.clientX - rect.left, event.clientY - rect.top, rect.width, rect.height); if (cell) { state.selected = { c: cell.c, r: cell.r }; setStatus('Hexágono ' + cell.c + '-' + cell.r + ' seleccionado.'); draw(); } }); $('survey').addEventListener('click', survey); $('claim').addEventListener('click', claim); $('end').addEventListener('click', endTurn); $('start').addEventListener('click', startCampaign); $('pause').addEventListener('click', togglePause); $('canvas').addEventListener('contextmenu', event => event.preventDefault()); window.addEventListener('resize', resize); window.addEventListener('keydown', event => { const keyName = event.key.toLowerCase(); if (keyName === 's') survey(); if (keyName === 'a') claim(); if (keyName === 'e') endTurn(); if (keyName === 'p') togglePause(); }); resize(); beginScenario(0); draw();
